### ISSUE TITLE
プロジェクトのモダン化

### ISSUE THREAD

**Issue by mizdra** [odanado/PokemonGoIVCalculator#6]
質の向上のためにこのプロジェクトをモダン化しませんか?
このプロジェクトは今後、さらなる開発がされていくと思っています。
そのためにも不適切なコードの除去、一部機能の自動化を目指し、開発しやすく、メンテナンスのしやすい環境を構築してみませんか?

私の具体的な提案内容は以下の通りです。
1. [npm](https://www.npmjs.com/)を導入してnpmパッケージを利用できるようにする (パッケージの管理)
2. [eslint](http://eslint.org/)を導入してコードをlintする (不適切なコードの検出・修正)
3. [gh-pages](https://www.npmjs.com/package/gh-pages)でデプロイを自動化する

また、npm package化することで以下のことも実現できます。
- モダンなjsコードに書き換えて、babelで古いブラウザ向けにトランスパイル (ソースコードをモダン化しつつ、サポートブラウザは変わらない!)
- mochaを導入してコードをtestする
- データセット(pokedex)をjsonファイル化し、build時にそれをapp.js中に展開する(データと処理の切り分け)

手順は以下の通りです。
# 準備

npmを導入する都合上、ディレクトリ構造を変更することをお勧めします。(以下で説明する`eslint`や`gh-pages`といったnpm packagesが扱いやすくなります)
まず、以下が現状のディレクトリです。

```
PokemonGoIVCalculator
├ css/
│ └ dashboard.css
├ js/
│ └ app.js 
├ index.html
└ LICENSE
```

これを以下のように変更します。

```
PokemonGoIVCalculator
├ src/
│ ├ css/
│ │ └ dashboard.css
│ ├ js/
│ │ └ app.js 
│ └ index.html
└ LICENSE
```
# npmを導入してnpmパッケージを利用できるようにする

npmはNode.js向けのパッケージマネージャです。npmを導入することで公開リポジトリ上にある「npm packages」と呼ばれる他人が書いたコードを簡単に自分のプロジェクトに取り入れることができます。

プロジェクトルートでコマンドラインから`npm init`を実行して下さい。プロジェクトルートに`package.json`nが生成され、そこにnpmに関する設定が書き込まれていきます。`npm init`コマンドは対話形式でnpmに関する設定を決定します。

以下は例です。

``` bash
$ cd PokemonGoIVCalculator
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (PokemonGoIVCalculator) pokemongo-iv-calculator
version: (1.0.0) 0.0.1
description: ポケモンGO個体値計算機
entry point: (index.js)
test command:
git repository: (https://github.com/odanado/PokemonGoIVCalculator.git)
keywords:
author: odanado
license: (MIT) MIT
About to write to /Users/mizdra/src/github.com/odanado/PokemonGoIVCalculator/package.json:

{
  "name": "pokemongo-iv-calculator",
  "version": "0.0.1",
  "description": "ポケモンGO個体値計算機",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/odanado/PokemonGoIVCalculator.git"
  },
  "author": "odanado",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/odanado/PokemonGoIVCalculator/issues"
  },
  "homepage": "https://github.com/odanado/PokemonGoIVCalculator#readme"
}


Is this ok? (yes) yes
```

設定しておくべき値は`name`(プロジェクトの名前, 大文字は使えません, 慣例で単語の区切りをハイフンでつなぎます), `version`(プロジェクトのバージョン, 通常、1.0.0は正式版を表します), `description`(プロジェクトの説明), `author`, `license`です。

これで`npm install -D eslint`などを実行すると npm package がプロジェクトにインストールされ、そのプロジェクト名が`package.json`に保存されるようになります。
# eslintを導入してコードをlintする

eslintはJavaScriptコードをlintするための npm package です。
以下のサイトを参考に、プロジェクトに eslint を導入します。(`npm install -D eslint`)
- [ESLint 最初の一歩 - Qiita ](http://qiita.com/mysticatea/items/f523dab04a25f617c87d)

[npm-scripts](https://docs.npmjs.com/misc/scripts) に `"lint": "eslint"`を設定しておくと`npm run lint`コマンドで lint が実行できるようになります。lint 対象とするjsファイル郡は`./src/js/*`とすると良いかと思います。
# gh-pagesでデプロイを自動化する

[gh-pages](https://www.npmjs.com/package/gh-pages) を使うことでgh-pagesにチェックアウトし、生成物をcommit、pushといった作業を自動化してくれます。
以下のサイトを参考にプロジェクトに gh-pages を導入します。(`npm install -D gh-pages`)
- [npm run deploy で GitHub Pages にお手軽デプロイ - Qiita](http://qiita.com/star__hoshi/items/490959aee12dbf528f7c)

[npm-scripts](https://docs.npmjs.com/misc/scripts) に `"deploy": "gh-pages -d ./src"`を設定しておくと`npm run deploy`コマンドでデプロイが実行できるようになります。

今後は変更内容をgh-pagesブランチ以外(master, developなど)にコミットし、サイトを更新したいときは`npm run deploy`を実行するという流れになります。

---

以上が私の提案となります。ご検討よろしくお願いします。

**Comment by odanado** [comment]
提案ありがとうございます．  
fix-to-modernブランチで作業を行い完了しました．何かご指摘あればよろしくお願いします．
https://github.com/odanado/PokemonGoIVCalculator/tree/fix-to-modern

**Comment by mizdra** [comment]
お引受けいただきありがとうございます! 作業お疲れ様です。

先程コードを拝見しました。とても良いと思います。

提案があるのですが、このissueの作業を終えた後に自動でlintするためにCIツール(例えばTravisCI)を導入してみてはいかがでしょう? 導入時の設定は以下が参考になるかと思います。
- [Building a Node.js project - Travis CI](https://docs.travis-ci.com/user/languages/javascript-with-nodejs)

以上、よろしくお願いします。

**Comment by odanado** [comment]
ありがとうございます．
comma-dangleをエラーにし対応しました．

CIツールの導入は私も考えていましたので，情報の提供ありがとうございます．
